"""TLS boundary: one owner supplies data, feature modules consume this contract."""
from __future__ import annotations

from typing import Any, Protocol


class TLSProvider(Protocol):
    def get_user(self, user_id: str) -> dict[str, Any] | None: ...
    def get_courses(self, user_id: str) -> list[dict[str, Any]]: ...
    def get_assignments(self, user_id: str) -> list[dict[str, Any]]: ...
    def get_lectures(self, user_id: str) -> list[dict[str, Any]]: ...
    def get_notices(self, user_id: str) -> list[dict[str, Any]]: ...
    def get_resources(self, user_id: str) -> list[dict[str, Any]]: ...
